<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SERLiveMonitoring</RootNamespace>
    <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="7.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="MudBlazor" Version="9.7.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="System.IO.Ports" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="SERLiveMonitoring.Tests\**" />
    <Content Remove="SERLiveMonitoring.Tests\**" />
    <EmbeddedResource Remove="SERLiveMonitoring.Tests\**" />
    <None Remove="SERLiveMonitoring.Tests\**" />
  </ItemGroup>

</Project>
